site_name: Notes
site_url: https://zoro0rkd.github.io/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
nav:
  - 홈: index.md
  - AI 모델 개발:
      - 아키텍처 설계: AI-모델-아키텍처-설계-‐-NEW.md
      - 학습과 평가: AI-모델-학습과-평가-‐-NEW.md
  - 유용한 사이트: 유용한-사이트.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.linkify
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search  # 기본 내장 (Lunr 기반)
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js